# Generated by Django 3.2.5 on 2022-03-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20220312_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='numbers',
            new_name='number',
        ),
    ]
